name: Prettier code formatter

on:
  push:
    branches:
      - master
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
      - name: Install Prettier 💾
        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
      - name: Prettier Auto-fix 🔧
        run: npx prettier . --write
      - name: Commit formatting fixes 💾
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix Prettier formatting"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
